# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uen', models.TextField(max_length=1000)),
                ('issuance_agency_id', models.TextField(max_length=1000)),
                ('uen_status', models.TextField(max_length=1000)),
                ('entity_name', models.TextField(max_length=1000)),
                ('entity_type', models.TextField(max_length=1000)),
                ('uen_issue_date', models.DateField()),
                ('reg_street_name', models.TextField(max_length=1000)),
                ('reg_postal_code', models.TextField(max_length=1000)),
            ],
        ),
    ]
